version: 2.1

parameters:
  is_pr:
    type: boolean
    default: false

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

workflows:
  build_and_push_image:
    when: << pipeline.parameters.is_pr >>
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws-dev
          create-repo: true
          dockerfile: DockerFile.prod
          path: .
          repo: pokeapp
          tag: "$CIRCLE_SHA1"
