version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@2.0.0
  aws-ecr: circleci/aws-ecr@8.1.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws-dev
          create-repo: true
          dockerfile: DockerFile.prod
          path: .
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "$CIRCLE_SHA1"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          steps:
            - aws-cli/setup:
              profile-name: circle-ci-pokeapp
              aws-access-key-id: "${AWS_ACCESS_KEY_ID}"
              aws-secret-access-key: "${AWS_SECRET_ACCESS_KEY}"
          cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-cluster
          container-image-name-updates: container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}
          family: ${AWS_RESOURCE_NAME_PREFIX}-service
