version: 2.1

orbs:
  aws-ecs: circleci/aws-ecs@4.0.0
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@8.1.3

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          context: aws-dev
          create-repo: true
          dockerfile: DockerFile.prod
          path: .
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          tag: "$CIRCLE_SHA1"
      - aws-ecs/deploy_service_update:
          requires:
            - aws-ecr/build-and-push-image
          auth:
            - aws-cli/setup:
              profile-name: circle-ci-pokeapp
              role: arn:aws:iam::730335586083:user/circle-ci-pokeapp
          cluster: ${AWS_RESOURCE_NAME_PREFIX}-cluster
          container_image_name_updates: container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}
          family: ${AWS_RESOURCE_NAME_PREFIX}-service
          profile: circle-ci-pokeapp
