# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0

jobs:
  aws-ecr:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.11
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          repo: circleci-push-image-demo
          tag: latest,$CIRCLE_SHA1

workflows:
  build-and-push-to-ecr:
    jobs:
      - aws-ecr:
          context:
            - AWS-ECR-DEMO
          filters:
            branches:
              only:
                - main
