import "./globals.css";
import type { Metadata } from "next";
import { ApolloWrapper } from "../../components/ApolloWrapper/ApolloWrapper";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "PokeApp",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ApolloWrapper>
        <body className={roboto.className}>{children}</body>
      </ApolloWrapper>
    </html>
  );
}
