import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import GlobalProvider from "../../lib/GlobalProvider/ReduxWrapper";
export const metadata: Metadata = {
  title: "PokeApp | Pokedex",
  description: "Generated by create next apps",
};

const roboto = Roboto({
  weight: "400",
  style: "normal",
  subsets: ["latin"],
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
