import { AppBar } from "../../components/AppBar/AppBar";
import HomePageBody from "../../components/HomePageBody/Index";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "PokeApp | Pokedex",
  description: "Generated by create next apps",
};
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between  h-100">
      <AppBar />
      <HomePageBody />
    </main>
  );
}
