import { AppBar } from "../../components/AppBar/AppBar";
import GlobalProvider from "../../lib/GlobalProvider/ReduxWrapper";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "PokeApp | Pokedex",
  description: "Generated by create next apps",
};
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24 h-100">
      <GlobalProvider>
        <AppBar />
      </GlobalProvider>
    </main>
  );
}
